apiVersion: apps/v1
kind: Deployment
metadata:
  name: azedge-iothub-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azedge-iothub-connector
  template:
    metadata:
      labels:
        app: azedge-iothub-connector
    spec:
      serviceAccountName: azedge-dmqtt-module-client-sa
      containers:
      - name: azedge-iothub-connector
        image: e4khubconnector.azurecr.io/azedge-iothub-connector:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: mqtt-client-token
          mountPath: /var/run/secrets/tokens
        - name: ca
          mountPath: /certs/ca.pem 
          subPath: ca.pem
        - name: routes-volume
          mountPath: /routes
          readOnly: true
        env:
        - name: Logging__LogLevel__Default
          value: Information
        - name: ConnectionStrings__EdgeDevice
          valueFrom:
            secretKeyRef:
              name: e4k-gateway-secrets
              key: edgeDevice
        - name: ConnectionStrings__Broker
          valueFrom:
            secretKeyRef:
              name: e4k-gateway-secrets
              key: Broker
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "true"
        - name: ROUTES_DIRECTORY_PATH
          value: "/routes/"
        - name: ROUTES_FILE_NAME
          value: "routes.cnf"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      imagePullSecrets: 
      - name: e4kacr
      volumes:
      - name: mqtt-client-token
        projected:
          sources:
          - serviceAccountToken:
              path: mqtt-client-token
              audience: azedge-iothub-connector-module
      - name: routes-volume
        configMap:
          name: azedge-iothubconnector-routesmap
      - name: ca 
        configMap:
          name: client-ca 
          items:
            - key: ca.pem 
              path: ca.pem
        
---
apiVersion: v1
kind: Service
metadata:
  name: azedge-iothub-connector-svc
spec:
  selector:
    app: azedge-iothub-connector
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
